### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by methodik** [digiltd/alfred-google-url-shortener#1]
As a user, when I run the command `shorten {URL}` I am shown a native notification that tells me the URL has been shortened

However the shortened URL isn't added to my clipboard which blocks me from using the shortened URL

I've been using the plugin for about 6 months and it's always worked great, until yesterday.

Environment: MacBook Pro '18 | OSX Mohave 10.14.3 | Latest version of Alfred

**Comment by chmurph2** [comment]
Unfortunately, Google shutdown https://goo.gl/.

https://www.engadget.com/2018/03/30/google-shutting-down-goo-gl-url-shortening-service/

**Comment by AnthoPakPak** [comment]
Too bad, it was really handy… 
Does anyone has a correct alternative working well with Alfred ? Thanks 👌

**Comment by digiltd** [comment]
yep, sorry

try http://www.packal.org/workflow/shorten-url - works for me
